### ISSUE TITLE
List App\Model order by Average Rating?

### ISSUE THREAD

**Issue by maximusblade** [willvincent/laravel-rateable#11]
I'm having trouble finding  out how to list a ratable models
Order by average rating ?

I think this is completely the wrong way to go about it...but this is what I have 

` public function scopeTopRatedThisWeek($query)
    {
        return $this->ratings()->where('ratings.created_at', '>=', Carbon::now()->startOfWeek())->avg('rating');
    }`

**Comment by willvincent** [comment]
The issue here is that average rating is calculated on the fly, so you'll need to do that calculation with a raw select.. I answered a similar issue to this on laracasts a while back. This should get you pointed in the right direction:

https://laracasts.com/discuss/channels/eloquent/orderby-computed-related-attribute
