### ISSUE TITLE
migrate

### ISSUE THREAD

**Issue by esginmurat** [willvincent/laravel-rateable#31]
Hello. Thanks for laravel-rateable. 

i am using laravel 5.1.46 on ubuntu 16.04 php 7

First I did this:
1-`composer require laravel-rateable`
after, add this line my config/app.php
2-`willvincent\Rateable\RateableServiceProvider::class,`
after,
3-`php artisan rateable:migration`
i got this error:

` php artisan rateable:migration

  [InvalidArgumentException]
  There are no commands defined in the "rateable" namespace.
`

Please help me. thanks..
Regards.

**Comment by willvincent** [comment]
Not sure why the command wouldn't work, but you could always manually copy the migration file from within the codebase instead of populating it with the command.

Literally, all that command does is copy the [create_ratings_table.php](https://github.com/willvincent/laravel-rateable/blob/master/src/migrations/create_ratings_table.php) file into your migrations directory, prefixing it with the current timestamp.

**Comment by vimuths123** [comment]
Seems like the package has changed a bit. You have to do these instead,
`php artisan vendor:publish --provider="willvincent\Rateable\RateableServiceProvider" --tag="migrations"`
`php artisan migrate`

This is the official [doc](https://packagist.org/packages/willvincent/laravel-rateable)

**Comment by willvincent** [comment]
Pretty sure it was a laravel change that caused that, rather than a change to this package. But we probably ought to update the install info.  Want to submit a pull request @vimuths123? 🙂
